In [8]:
import pandas as pd
import numpy as np

Se carga la base de datos analizar en un dataframe

In [9]:
from pandas.io.excel import read_excel

url ="https://raw.githubusercontent.com/Neo3009/BasesdeDatosgrupo2/main/HOW_2FTE_SEX_JOB_NB_A-filtrado-2023-03-23.csv"
df = pd.read_csv(url)
df

,ref_area.label,indicator.label,source.label,sex.label,classif1.label,time,obs_value
0,Afganist치n,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2020,706.395
1,Afganist치n,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2020,588.663
2,Angola,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2023,432.152
3,Angola,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2023,360.127
4,Angola,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2022,496.558
...,...,...,...,...,...,...,...
2791,Zimbabwe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2022,159.793
2792,Zimbabwe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2021,399.488
2793,Zimbabwe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2021,332.907
2794,Zimbabwe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2020,594.748
2795,Zimbabwe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2020,495.624

Se valida las columnas existentes

In [10]:
df.columns

Index(['ref_area.label', 'indicator.label', 'source.label', 'sex.label',
       'classif1.label', 'time', 'obs_value'],
      dtype='object')

In [ ]:
La variable que nos interesa validamos datos unicos

In [11]:
df.columns=['ref_area.label', 'indicator.label', 'source.label', 'sex.label', 'classif1.label', 'time', 'obs_value']
df['ref_area.label'].unique()

array(['Afganist치n', 'Angola', 'Albania', 'Emiratos Arabes Unidos',
       'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaiy치n',
       'Burundi', 'B칠lgica', 'Benin', 'Burkina Faso', 'Bangladesh',
       'Bulgaria', 'Bahrein', 'Bahamas', 'Bosnia y Herzegovina',
       'Belar칰s', 'Belice', 'Bolivia', 'Brasil', 'Barbados',
       'Brunei Darussalam', 'Bhut치n', 'Botswana',
       'Rep칰blica Centroafricana', 'Canad치', 'Islas Anglonormandas',
       'Suiza', 'Chile', 'China', "C칪te d'Ivoire", 'Camer칰n',
       'Congo, Rep. Dem. del', 'Congo', 'Colombia', 'Comoras',
       'Cabo Verde', 'Costa Rica', 'Cuba', 'Chipre', 'Chequia',
       'Alemania', 'Djibouti', 'Dinamarca', 'Rep칰blica Dominicana',
       'Argelia', 'Ecuador', 'Egipto', 'Eritrea', 'Sahara Occidental',
       'Espa침a', 'Estonia', 'Etiop칤a', 'Finlandia', 'Fiji', 'Francia',
       'Gab칩n', 'Reino Unido', 'Georgia', 'Ghana', 'Guinea', 'Gambia',
       'Guinea-Bissau', 'Guinea Ecuatorial', 'Grecia', 'Guatemala',
       'Guam', 'Guyana', 'Hong Kong, China', 'Honduras', 'Croacia',
       'Hait칤', 'Hungr칤a', 'Indonesia', 'India', 'Irlanda',
       'Ir치n, Rep칰blica Isl치mica del', 'Iraq', 'Islandia', 'Israel',
       'Italia', 'Jamaica', 'Jordania', 'Jap칩n', 'Kazajst치n', 'Kenya',
       'Kirguist치n', 'Camboya', 'Corea, Rep칰blica de', 'Kuwait',
       'Lao, Rep칰blica Democr치tica Popular Lao', 'L칤bano', 'Liberia',
       'Libia', 'Santa Luc칤a', 'Sri Lanka', 'Lesotho', 'Lituania',
       'Luxemburgo', 'Letonia', 'Macao, China', 'Marruecos',
       'Moldova, Rep칰blica de', 'Madagascar', 'Maldivas', 'M칠xico',
       'Macedonia del Norte', 'Mal칤', 'Malta', 'Myanmar', 'Montenegro',
       'Mongolia', 'Mozambique', 'Mauritania', 'Mauricio', 'Malawi',
       'Malasia', 'Namibia', 'Nueva Caledonia', 'N칤ger', 'Nigeria',
       'Nicaragua', 'Pa칤ses Bajos', 'Noruega', 'Nepal', 'Nueva Zelandia',
       'Om치n', 'Pakist치n', 'Panam치', 'Per칰', 'Filipinas',
       'Papua Nueva Guinea', 'Polonia', 'Puerto Rico',
       'Corea, Rep칰blica Popular Democr치tica de', 'Portugal', 'Paraguay',
       'Territorio palestino ocupado', 'Polinesia Francesa', 'Qatar',
       'Rumania', 'Rusia, Federaci칩n de', 'Rwanda', 'Arabia Saudita',
       'Senegal', 'Singapur', 'Islas Salom칩n', 'Sierra Leona',
       'El Salvador', 'Somalia', 'Serbia', 'Sud치n',
       'Santo Tom칠 y Pr칤ncipe', 'Suriname', 'Eslovaquia', 'Eslovenia',
       'Suecia', 'Eswatini', 'Rep칰blica Arabe Siria', 'Chad', 'Togo',
       'Tailandia', 'Tayikist치n', 'Turkmenist치n', 'Timor-Leste', 'Tonga',
       'Trinidad y Tabago', 'T칰nez', 'T칲rkiye', 'Taiwan, China',
       'Tanzan칤a, Rep칰blica Unida de', 'Uganda', 'Ucrania', 'Uruguay',
       'Estados Unidos', 'Uzbekist치n', 'San Vicente y las Granadinas',
       'Venezuela, Rep칰blica Bolivariana de', 'Islas V칤rgenes Americanas',
       'Viet Nam', 'Vanuatu', 'Samoa', 'Mundo', 'Mundo: Ingreso bajo',
       'Mundo: Ingreso mediano bajo', 'Mundo: Ingreso mediano alto',
       'Mundo: Ingreso alto', '츼frica', '츼frica: Ingreso bajo',
       '츼frica: Ingreso mediano bajo', '츼frica: Ingreso mediano alto',
       'Norte de 츼frica', 'Norte de 츼frica: Ingreso mediano bajo',
       '츼frica subsahariana', '츼frica subsahariana: Ingreso bajo',
       '츼frica subsahariana: Ingreso mediano bajo',
       '츼frica subsahariana: Ingreso mediano alto', '츼frica central',
       '츼frica Oriental', '츼frica del Sur', '츼frica Occidental',
       'Am칠ricas', 'Am칠ricas: Ingreso mediano bajo',
       'Am칠ricas: Ingreso mediano alto', 'Am칠ricas: Ingreso alto',
       'Am칠rica Latina y el Caribe',
       'Am칠rica Latina y el Caribe: Ingreso mediano bajo',
       'Am칠rica Latina y el Caribe: Ingreso mediano alto',
       'Am칠rica Latina y el Caribe: Ingreso alto', 'Caribe',
       'Am칠rica Central', 'Am칠rica del Sur', 'Am칠rica del Norte',
       'Am칠rica del Norte: Ingreso alto', 'Estados 츼rabes',
       'Estados 츼rabes: Ingreso mediano bajo',
       'Estados 츼rabes: Ingreso mediano alto',
       'Estados 츼rabes: Ingreso alto', 'Asia y el Pac칤fico',
       'Asia y el Pac칤fico: Ingreso bajo',
       'Asia y el Pac칤fico: Ingreso mediano bajo',
       'Asia y el Pac칤fico: Ingreso mediano alto',
       'Asia y el Pac칤fico: Ingreso alto', 'Asia Oriental',
       'Asia Oriental: Ingreso alto', 'Asia sudoriental y el Pac칤fico',
       'Asia sudoriental y el Pac칤fico: Ingreso mediano bajo',
       'Asia sudoriental y el Pac칤fico: Ingreso mediano alto',
       'Asia sudoriental y el Pac칤fico: Ingreso alto', 'Asia Sudoriental',
       'Islas del Pac칤fico', 'Asia meridonal',
       'Asia meridonal: Ingreso mediano bajo', 'Europa y Asia Central',
       'Europa y Asia Central: Ingreso mediano bajo',
       'Europa y Asia Central: Ingreso mediano alto',
       'Europa y Asia Central: Ingreso alto',
       'Europa del Norte, Sur y Occidental',
       'Europa del Norte, Sur y Occidental: Ingreso mediano alto',
       'Europa del Norte, Sur y Occidental: Ingreso alto',
       'Norte de Europa', 'Sur de Europa', 'Europa occidental',
       'Europa oriental', 'Europa oriental: Ingreso mediano alto',
       'Europa oriental: Ingreso alto', 'Asia Central',
       'Asia Central y Occidental: Ingreso mediano bajo',
       'Asia Central y Occidental: Ingreso mediano alto',
       'Asia Central y Occidental: Ingreso alto',
       'Asia Central y Occidental', 'Asia occidental', 'Uni칩n Europea 28',
       'G20', 'ASEAN', 'BRICS', 'Mundo sin los BRICS', 'G7', 'OMNA',
       'Liga Arabe', 'CARICOM', 'Uni칩n Europea 27',
       'Estados 츼rabes: Ingreso bajo', 'APEC', 'Yemen', 'Sud치frica',
       'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
Se realiza el filtro por los paises que se requiere

In [12]:
filtro= df['ref_area.label'].isin(['Argentina', 'Bahamas',
'Belice',
'Bolivia',
'Brasil',
'Barbados',
'Chile',
'Colombia',
'Cuba',
'Ecuador',
'Guatemala',
'Guyana',
'Honduras',
'Hait칤',
'Jamaica',
'M칠xico',
'Nicaragua',
'Panam치',
'Per칰',
'Paraguay',
'Suriname',
'Uruguay',
'Venezuela',
'Am칠rica Latina y el Caribe',
'Am칠rica Latina y el Caribe: Ingresomedianobajo',
'Am칠rica Latina y el Caribe: Ingresomedianoalto',
'Am칠rica Latina y el Caribe: Ingresoalto',
'Caribe',
'Am칠rica Central',
'Am칠rica del Sur'])
print(filtro)

0       False
1       False
2       False
3       False
4       False
        ...
2791    False
2792    False
2793    False
2794    False
2795    False
Name: ref_area.label, Length: 2796, dtype: bool

In [ ]:
Se genera el dataframe con el filtro realizado con anterioridad

In [13]:
df_filtrado = df.loc[filtro]
df_filtrado

,ref_area.label,indicator.label,source.label,sex.label,classif1.label,time,obs_value
26,Argentina,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2023,23.444
27,Argentina,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2023,19.537
28,Argentina,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2022,-241.113
29,Argentina,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2022,-200.928
30,Argentina,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2021,503.796
...,...,...,...,...,...,...,...
1927,Am칠rica del Sur,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2020,26248.073
1928,Am칠rica del Sur,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Hombres,Equivalencia a tiempo completo: Basado en 40 h...,2020,17120.813
1929,Am칠rica del Sur,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Hombres,Equivalencia a tiempo completo: Basado en 48 h...,2020,14267.344
1930,Am칠rica del Sur,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Mujeres,Equivalencia a tiempo completo: Basado en 40 h...,2020,14376.874
1931,Am칠rica del Sur,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Mujeres,Equivalencia a tiempo completo: Basado en 48 h...,2020,11980.728

Filtro de una sola variable

In [15]:
#Filtrar los registros de Latinoamerica y generar base final
df1 = df.loc[df["ref_area.label"] == ('Am칠rica Latina y el Caribe')]
df1

,ref_area.label,indicator.label,source.label,sex.label,classif1.label,time,obs_value
1820,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2023,-87.559
1821,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2023,-72.966
1822,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2022,-3130.064
1823,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2022,-2608.387
1824,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2021,12941.118
1825,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2021,10784.265
1826,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Hombres,Equivalencia a tiempo completo: Basado en 40 h...,2021,6502.994
1827,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Hombres,Equivalencia a tiempo completo: Basado en 48 h...,2021,5419.161
1828,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Mujeres,Equivalencia a tiempo completo: Basado en 40 h...,2021,6438.124
1829,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Mujeres,Equivalencia a tiempo completo: Basado en 48 h...,2021,5365.103
1830,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 40 h...,2020,46892.211
1831,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Total,Equivalencia a tiempo completo: Basado en 48 h...,2020,39076.842
1832,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Hombres,Equivalencia a tiempo completo: Basado en 40 h...,2020,26651.612
1833,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Hombres,Equivalencia a tiempo completo: Basado en 48 h...,2020,22209.676
1834,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Mujeres,Equivalencia a tiempo completo: Basado en 40 h...,2020,20240.599
1835,Am칠rica Latina y el Caribe,Horas de trabajo perdidas debido a la crisis d...,OIT - Estimaciones Modeladas,Sexo: Mujeres,Equivalencia a tiempo completo: Basado en 48 h...,2020,16867.166