In [24]:
## Librerías

import pandas as pd
import numpy as np

In [25]:
from pandas.io.excel import read_excel
# Carpeta de Bases de datos https://github.com/Neo3009/BasesdeDatosgrupo2

url ="https://raw.githubusercontent.com/Neo3009/BasesdeDatosgrupo2/main/final.csv"
df0 = pd.read_csv(url)
df0

,country,region,health_index,obese_rate,suicide_rate,democracies_rate,hdr_rate,life_Exp,gpi,iq_rate,"Deaths per 1,000 live births",gdp_usd,Ipc
0,Afghanistan,ASIA (EX. NEAR EAST),28.8,5.5,4.1,0.32,0.511,62.879,3.554,82.12,44.97,490,147.0
1,Albania,EASTERN EUROPE,45.0,21.7,4.3,6.11,0.795,76.833,1.761,81.75,8.76,5334,111.0
2,Algeria,NORTHERN AFRICA,26.2,27.4,2.5,3.77,0.748,77.129,2.146,76.00,19.46,3287,253.0
3,Angola,SUB-SAHARAN AFRICA,29.1,8.2,6.1,3.37,0.581,61.929,1.982,75.10,48.34,1637,142.0
4,Argentina,LATIN AMER. & CARIB,54.4,28.3,8.4,6.81,0.845,76.064,1.911,86.63,7.61,8549,1029.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Uruguay,LATIN AMER. & CARIB,40.3,27.9,21.2,8.85,0.817,78.000,1.795,87.59,5.32,15648,261.0
112,Uzbekistan,C.W. OF IND. STATES,39.0,16.6,8.0,2.12,0.720,71.674,2.001,89.01,12.46,1730,NaN
113,Venezuela,LATIN AMER. & CARIB,20.9,25.6,2.1,2.11,0.711,71.105,2.798,82.99,21.06,1670,5654207.0
114,Zambia,SUB-SAHARAN AFRICA,26.5,8.1,7.3,5.72,0.584,61.803,1.841,68.43,41.66,905,364.0
115,Zimbabwe,SUB-SAHARAN AFRICA,32.4,15.5,14.1,2.92,0.571,59.391,2.350,74.01,37.93,1418,13114.0

## Back Up del archivo paises en github
"https://github.com/LarryTobonS/Files/blob/main/Paises.xlsx"

In [26]:
## Importar tabla de paises para generar códigos
tps = read_excel("Paises.xlsx",sheet_name="Codigos")
tps

         country  Code
0     Afganistán     4
1    Afghanistan     4
2        Albania     8
3       Alemania   276
4        Algeria    12
..           ...   ...
321        Yemen   887
322       Yibuti   262
323       Zambia   894
324     Zimbabue   716
325     Zimbabwe   716

[326 rows x 2 columns]

In [27]:
## Traer el código del país al df0

df1 = pd.merge(df0,tps,how="left",left_on="country",right_on="country")

## Ordenar columnas para que Code salga de primero
df1 = df1[['Code','country', 'region', 'health_index', 'obese_rate', 'suicide_rate',
       'democracies_rate', 'hdr_rate', 'life_Exp', 'gpi', 'iq_rate',
       'Deaths per 1,000 live births', 'gdp_usd', 'Ipc']]

df1

,Code,country,region,health_index,obese_rate,suicide_rate,democracies_rate,hdr_rate,life_Exp,gpi,iq_rate,"Deaths per 1,000 live births",gdp_usd,Ipc
0,4,Afghanistan,ASIA (EX. NEAR EAST),28.8,5.5,4.1,0.32,0.511,62.879,3.554,82.12,44.97,490,147.0
1,8,Albania,EASTERN EUROPE,45.0,21.7,4.3,6.11,0.795,76.833,1.761,81.75,8.76,5334,111.0
2,12,Algeria,NORTHERN AFRICA,26.2,27.4,2.5,3.77,0.748,77.129,2.146,76.00,19.46,3287,253.0
3,24,Angola,SUB-SAHARAN AFRICA,29.1,8.2,6.1,3.37,0.581,61.929,1.982,75.10,48.34,1637,142.0
4,32,Argentina,LATIN AMER. & CARIB,54.4,28.3,8.4,6.81,0.845,76.064,1.911,86.63,7.61,8549,1029.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,858,Uruguay,LATIN AMER. & CARIB,40.3,27.9,21.2,8.85,0.817,78.000,1.795,87.59,5.32,15648,261.0
112,860,Uzbekistan,C.W. OF IND. STATES,39.0,16.6,8.0,2.12,0.720,71.674,2.001,89.01,12.46,1730,NaN
113,862,Venezuela,LATIN AMER. & CARIB,20.9,25.6,2.1,2.11,0.711,71.105,2.798,82.99,21.06,1670,5654207.0
114,894,Zambia,SUB-SAHARAN AFRICA,26.5,8.1,7.3,5.72,0.584,61.803,1.841,68.43,41.66,905,364.0
115,716,Zimbabwe,SUB-SAHARAN AFRICA,32.4,15.5,14.1,2.92,0.571,59.391,2.350,74.01,37.93,1418,13114.0

In [28]:
#Filtrar los registros de Latinoamerica y generar base final
df = df1.loc[df1["region"] == "LATIN AMER. & CARIB"]
df

,Code,country,region,health_index,obese_rate,suicide_rate,democracies_rate,hdr_rate,life_Exp,gpi,iq_rate,"Deaths per 1,000 live births",gdp_usd,Ipc
4,32,Argentina,LATIN AMER. & CARIB,54.4,28.3,8.4,6.81,0.845,76.064,1.911,86.63,7.61,8549,1029.0
13,68,Bolivia,LATIN AMER. & CARIB,29.9,20.2,6.2,4.65,0.718,64.928,1.989,76.53,20.72,3018,108.0
16,76,Brazil,LATIN AMER. & CARIB,51.2,22.1,6.9,6.86,0.765,73.425,2.465,83.38,13.13,6728,6408.0
21,152,Chile,LATIN AMER. & CARIB,56.2,28.0,9.0,7.92,0.851,79.519,1.840,87.89,5.77,12880,127.0
23,170,Colombia,LATIN AMER. & CARIB,53.2,22.3,3.9,6.48,0.767,73.659,2.729,83.13,11.35,5213,124.0
24,188,Costa Rica,LATIN AMER. & CARIB,40.8,25.7,8.1,8.07,0.810,77.320,1.732,88.34,6.73,11995,111.0
26,192,Cuba,LATIN AMER. & CARIB,30.5,24.6,14.5,2.59,0.783,78.155,2.083,83.90,4.08,7999,NaN
29,214,Dominican Republic,LATIN AMER. & CARIB,34.5,27.6,4.9,6.45,0.756,74.170,1.990,82.05,27.87,7029,120.0
30,218,Ecuador,LATIN AMER. & CARIB,50.8,19.9,7.6,5.71,0.759,77.894,1.988,78.26,11.15,5516,110.0
32,222,El Salvador,LATIN AMER. & CARIB,40.8,24.6,6.1,5.72,0.673,71.475,2.231,69.63,11.08,3888,127.0
41,320,Guatemala,LATIN AMER. & CARIB,29.1,21.2,5.9,4.62,0.663,68.674,2.139,47.72,20.06,4349,167.0
42,328,Guyana,LATIN AMER. & CARIB,30.8,20.2,40.3,6.25,0.682,65.989,2.140,83.23,23.78,6765,137.0
43,340,Honduras,LATIN AMER. & CARIB,26.2,21.4,2.1,5.10,0.634,70.728,2.269,62.16,13.94,2284,399.0
52,388,Jamaica,LATIN AMER. & CARIB,31.8,24.7,2.4,7.13,0.734,70.629,1.990,75.08,11.43,4940,126.0
66,484,Mexico,LATIN AMER. & CARIB,57.0,28.9,5.3,5.57,0.779,74.832,2.612,87.73,11.77,8526,125.0
74,558,Nicaragua,LATIN AMER. & CARIB,36.3,23.7,4.4,2.69,0.660,74.615,2.334,52.69,13.79,1816,280.0
79,591,Panama,LATIN AMER. & CARIB,53.5,22.7,2.9,6.85,0.815,76.826,1.876,79.00,12.34,12244,108.0
81,600,Paraguay,LATIN AMER. & CARIB,40.3,20.3,6.0,5.86,0.728,70.475,1.976,84.04,16.18,5225,124.0
82,604,Peru,LATIN AMER. & CARIB,54.9,19.7,2.8,6.09,0.777,73.385,2.091,81.44,9.95,6027,107.0
111,858,Uruguay,LATIN AMER. & CARIB,40.3,27.9,21.2,8.85,0.817,78.000,1.795,87.59,5.32,15648,261.0
113,862,Venezuela,LATIN AMER. & CARIB,20.9,25.6,2.1,2.11,0.711,71.105,2.798,82.99,21.06,1670,5654207.0

In [29]:
## Exportar archivo transformado a CSV
df.to_csv('Datos_Macro.csv', index=False)